name: "Install & cache dependencies"

description: "Install dependencies and cache them for future runs"

inputs:
  # The path to the package-lock.json file
  skip-cache:
    description: "Skip caching dependencies"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.skip-cache == 'false'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.skip-cache == 'true'
      run: npm ci
      shell: bash
