name: "Install & cache dependencies"

description: "Install dependencies and cache them for future runs"

inputs:
  caching:
    description: "Cache dependencies"
    required: false
    default: "true"

outputs:
  cache-hit:
    description: "Whether the cache was used"
    value: ${{ steps.cache.outputs.cache-hit }}

  cache-used:
    description: "Whether the cache was used"
    value: ${{ steps.install.outputs.cache-used }}

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: |
        npm ci
        echo "cache-used=${{ inputs.caching == 'true' }}" >> $GITHUB_OUTPUT
      shell: bash
